import type { Movie, TVShow, Genre, ContinueWatching, UserPreferences } from '../types';

// Genres
export const genres: Genre[] = [
  { _id: '1', name: 'Action', slug: 'action' },
  { _id: '2', name: 'Adventure', slug: 'adventure' },
  { _id: '3', name: 'Animation', slug: 'animation' },
  { _id: '4', name: 'Comedy', slug: 'comedy' },
  { _id: '5', name: 'Crime', slug: 'crime' },
  { _id: '6', name: 'Documentary', slug: 'documentary' },
  { _id: '7', name: 'Drama', slug: 'drama' },
  { _id: '8', name: 'Fantasy', slug: 'fantasy' },
  { _id: '9', name: 'Horror', slug: 'horror' },
  { _id: '10', name: 'Mystery', slug: 'mystery' },
  { _id: '11', name: 'Romance', slug: 'romance' },
  { _id: '12', name: 'Sci-Fi', slug: 'sci-fi' },
  { _id: '13', name: 'Thriller', slug: 'thriller' },
  { _id: '14', name: 'Western', slug: 'western' },
  { _id: '15', name: 'Sports', slug: 'sports' },
];

// Movies
export const movies: Movie[] = [
  {
    _id: '1',
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival. Earth\'s future has been riddled by disasters, famines, and droughts.',
    releaseYear: 2014,
    duration: 169,
    rating: 8.6,
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    director: 'Christopher Nolan',
    thumbnail: 'https://image.tmdb.org/t/p/w500/gEU2QniL6E8AHt40H07A5KWYJL.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: true,
    isNewRelease: false,
    maturityRating: 'PG-13',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '2',
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.',
    releaseYear: 2008,
    duration: 152,
    rating: 9.0,
    genre: ['Action', 'Crime', 'Drama'],
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Gary Oldman'],
    director: 'Christopher Nolan',
    thumbnail: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8wYlsXQzEhRnJWE.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: true,
    isNewRelease: false,
    maturityRating: 'PG-13',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '3',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    releaseYear: 2010,
    duration: 148,
    rating: 8.8,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page', 'Tom Hardy'],
    director: 'Christopher Nolan',
    thumbnail: 'https://image.tmdb.org/t/p/w500/9gk7admal4ZLcnwnCSmYd2t8bU.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/s3TBrRGB1jav7y4argnzPkNPZKs.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: true,
    isNewRelease: false,
    maturityRating: 'PG-13',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French', 'German'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '4',
    title: 'The Matrix',
    description: 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
    releaseYear: 1999,
    duration: 136,
    rating: 8.7,
    genre: ['Action', 'Sci-Fi'],
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    director: 'Lana Wachowski',
    thumbnail: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9Gkd9EpXUkU4.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: 'FHD',
    isTrending: false,
    isNewRelease: true,
    maturityRating: 'R',
    language: 'English',
    subtitles: ['English', 'Spanish'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '5',
    title: 'Avengers: Endgame',
    description: 'After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.',
    releaseYear: 2019,
    duration: 181,
    rating: 8.4,
    genre: ['Action', 'Adventure', 'Drama'],
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson', 'Mark Ruffalo'],
    director: 'Anthony Russo',
    thumbnail: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: true,
    isNewRelease: false,
    maturityRating: 'PG-13',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French', 'Chinese'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '6',
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    releaseYear: 1994,
    duration: 154,
    rating: 8.9,
    genre: ['Crime', 'Drama'],
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
    director: 'Quentin Tarantino',
    thumbnail: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: 'FHD',
    isTrending: false,
    isNewRelease: true,
    maturityRating: 'R',
    language: 'English',
    subtitles: ['English', 'Spanish'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '7',
    title: 'The Shawshank Redemption',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    releaseYear: 1994,
    duration: 142,
    rating: 9.3,
    genre: ['Drama'],
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler'],
    director: 'Frank Darabont',
    thumbnail: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: 'FHD',
    isTrending: true,
    isNewRelease: false,
    maturityRating: 'R',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '8',
    title: 'Parasite',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    releaseYear: 2019,
    duration: 132,
    rating: 8.5,
    genre: ['Comedy', 'Drama', 'Thriller'],
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'],
    director: 'Bong Joon-ho',
    thumbnail: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/9PDCgOyLbRd8M8lMhCjQlZqTbGf.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: true,
    isNewRelease: true,
    maturityRating: 'R',
    language: 'Korean',
    subtitles: ['English', 'Spanish', 'French', 'Korean'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// TV Shows
export const tvShows: TVShow[] = [
  {
    _id: '101',
    title: 'Stranger Things',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    releaseYear: 2016,
    rating: 8.7,
    genre: ['Drama', 'Fantasy', 'Horror'],
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder', 'David Harbour'],
    creator: 'The Duffer Brothers',
    thumbnail: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYkJu64COcfe.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: true,
    isNewRelease: true,
    maturityRating: 'TV-14',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { episodeNumber: 1, title: 'Chapter One: The Vanishing of Will Byers', duration: 49, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
          { episodeNumber: 2, title: 'Chapter Two: The Weirdo on Maple Street', duration: 56, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
          { episodeNumber: 3, title: 'Chapter Three: Holly, Jolly', duration: 52, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
        ],
      },
      {
        seasonNumber: 2,
        title: 'Season 2',
        episodes: [
          { episodeNumber: 1, title: 'Chapter One: MADMAX', duration: 48, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
          { episodeNumber: 2, title: 'Chapter Two: Trick or Treat, Freak', duration: 56, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
        ],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '102',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.',
    releaseYear: 2008,
    rating: 9.5,
    genre: ['Crime', 'Drama', 'Thriller'],
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn', 'Dean Norris'],
    creator: 'Vince Gilligan',
    thumbnail: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tsRy63Mu5CU8etx1BHkT2AqLMJE.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: true,
    isNewRelease: false,
    maturityRating: 'TV-MA',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { episodeNumber: 1, title: 'Pilot', duration: 58, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
          { episodeNumber: 2, title: 'Cat\'s in the Bag...', duration: 48, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
        ],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '103',
    title: 'Game of Thrones',
    description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    releaseYear: 2011,
    rating: 9.2,
    genre: ['Action', 'Adventure', 'Drama', 'Fantasy'],
    cast: ['Emilia Clarke', 'Peter Dinklage', 'Kit Harington', 'Lena Headey'],
    creator: 'David Benioff',
    thumbnail: 'https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyve4z7w5tHn.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: true,
    isNewRelease: false,
    maturityRating: 'TV-MA',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French', 'German'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { episodeNumber: 1, title: 'Winter Is Coming', duration: 62, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
          { episodeNumber: 2, title: 'The Kingsroad', duration: 56, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
        ],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '104',
    title: 'The Crown',
    description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.',
    releaseYear: 2016,
    rating: 8.6,
    genre: ['Drama', 'History'],
    cast: ['Claire Foy', 'Olivia Colman', 'Imelda Staunton', 'Matt Smith'],
    creator: 'Peter Morgan',
    thumbnail: 'https://image.tmdb.org/t/p/w500/1DSpHrWyX7kL5Y5Y5Y5Y5Y5Y5Y5.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/wHa5KO34Va0hLMsP6TOLl15P9Yh.jpg',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    quality: '4K',
    isTrending: false,
    isNewRelease: true,
    maturityRating: 'TV-MA',
    language: 'English',
    subtitles: ['English', 'Spanish', 'French'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { episodeNumber: 1, title: 'Wolferton Splash', duration: 57, videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8' },
        ],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Continue Watching
export const continueWatching: ContinueWatching[] = [
  {
    movieId: '1',
    progress: 45,
    lastWatched: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    movieId: '3',
    progress: 72,
    lastWatched: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
  },
  {
    movieId: '101',
    progress: 30,
    lastWatched: new Date(Date.now() - 3 * 60 * 60 * 1000), // 3 hours ago
    season: 1,
    episode: 2,
  },
];

// User Preferences (default)
export const defaultPreferences: UserPreferences = {
  language: 'en',
  playbackQuality: 'auto',
  autoPlay: true,
  autoPlayNextEpisode: true,
  downloadQuality: 'high',
  subtitles: {
    enabled: false,
    language: 'en',
    fontSize: 'medium',
    backgroundColor: '#000000',
    textColor: '#FFFFFF',
  },
  notifications: {
    email: true,
    push: true,
    newReleases: true,
    recommendations: true,
  },
};

// Categories for browsing
export const categories = [
  { id: 'trending', name: 'Trending Now', type: 'mixed' },
  { id: 'new-releases', name: 'New Releases', type: 'mixed' },
  { id: 'top-rated', name: 'Top Rated', type: 'mixed' },
  { id: 'action', name: 'Action', type: 'genre' },
  { id: 'comedy', name: 'Comedy', type: 'genre' },
  { id: 'drama', name: 'Drama', type: 'genre' },
  { id: 'sci-fi', name: 'Sci-Fi & Fantasy', type: 'genre' },
  { id: 'thriller', name: 'Thrillers', type: 'genre' },
  { id: 'documentaries', name: 'Documentaries', type: 'genre' },
  { id: 'sports', name: 'Sports', type: 'genre' },
];
